'use strict';

/**
 * @readonly
 * @enum
 */
const Map = {
  SUMMONERS_RIFT_ORIGINAL: 1,
  SUMMONERS_RIFT_AUTUMN: 2,
  PROVING_GROUNDS: 3,
  TWISTED_TREELINE_ORIGINAL: 4,
  CRYSTAL_SCAR: 8,
  TWISTED_TREELINE_CURRENT: 10,
  SUMMONERS_RIGHT_CURRENT: 11,
  HOWLING_ABYSS: 12,
  BUTCHERS_BRIDGE: 14,
};

exports = module.exports = Map;
